{{- if .Values.ingress.dns }}
{{- $relname := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ if .Values.ingress.enableSSL }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: {{ .Values.ingress.certIssuer | quote}}
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
spec:
  {{ if .Values.ingress.enableSSL }}
  tls:
    - hosts:
        - {{ .Values.ingress.dns }}
      secretName: {{ .Release.Name }}-ssl-secret
  {{ end }}
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-api-gateway
              port:
                number: 80
{{- end }}